"""
Session Logger Module
Maintains history of user interactions, generated commands, and outputs.
"""

import os
from datetime import datetime
from typing import List, Dict


class SessionLogger:
    """Logs and maintains session history."""
    
    def __init__(self, log_to_file: bool = True):
        """
        Initialize the session logger.
        
        Args:
            log_to_file: Whether to save logs to a file (default: True)
        """
        self.session_history: List[Dict[str, str]] = []
        self.log_to_file = log_to_file
        self.session_start = datetime.now()
        
        if self.log_to_file:
            # Create log filename with timestamp
            timestamp = self.session_start.strftime("%Y%m%d_%H%M%S")
            self.log_filename = f"session_{timestamp}.log"
            
            # Write session start header
            self._write_to_file(f"=== Session Started: {self.session_start.strftime('%Y-%m-%d %H:%M:%S')} ===\n\n")
    
    def log_interaction(self, natural_language: str, generated_command: str, 
                        output: str, error: str = "", blocked: bool = False):
        """
        Log a complete interaction.
        
        Args:
            natural_language: User's natural language input
            generated_command: Command generated by LLM
            output: Command output
            error: Error message if any
            blocked: Whether the command was blocked by safety filter
        """
        timestamp = datetime.now()
        
        # Create log entry
        entry = {
            'timestamp': timestamp.strftime('%Y-%m-%d %H:%M:%S'),
            'natural_language': natural_language,
            'generated_command': generated_command,
            'output': output,
            'error': error,
            'blocked': blocked
        }
        
        # Add to history
        self.session_history.append(entry)
        
        # Write to file if enabled
        if self.log_to_file:
            self._write_interaction_to_file(entry)
    
    def _write_interaction_to_file(self, entry: Dict[str, str]):
        """Write an interaction entry to the log file."""
        log_text = f"[{entry['timestamp']}]\n"
        log_text += f"User Input: {entry['natural_language']}\n"
        log_text += f"Generated Command: {entry['generated_command']}\n"
        
        if entry['blocked']:
            log_text += "Status: BLOCKED\n"
        else:
            log_text += "Status: EXECUTED\n"
        
        if entry['output']:
            log_text += f"Output:\n{entry['output']}\n"
        
        if entry['error']:
            log_text += f"Error: {entry['error']}\n"
        
        log_text += "\n" + "-" * 80 + "\n\n"
        
        self._write_to_file(log_text)
    
    def _write_to_file(self, text: str):
        """Write text to the log file."""
        try:
            with open(self.log_filename, 'a', encoding='utf-8') as f:
                f.write(text)
        except Exception as e:
            print(f"Warning: Could not write to log file: {str(e)}")
    
    def get_history(self) -> List[Dict[str, str]]:
        """
        Get the session history.
        
        Returns:
            List of interaction entries
        """
        return self.session_history.copy()
    
    def get_recent_history(self, count: int = 10) -> List[Dict[str, str]]:
        """
        Get recent history entries.
        
        Args:
            count: Number of recent entries to return
            
        Returns:
            List of recent interaction entries
        """
        return self.session_history[-count:] if len(self.session_history) > count else self.session_history.copy()
    
    def clear_history(self):
        """Clear the session history (does not delete log file)."""
        self.session_history.clear()
    
    def get_session_summary(self) -> str:
        """
        Get a summary of the current session.
        
        Returns:
            Session summary string
        """
        total_interactions = len(self.session_history)
        blocked_count = sum(1 for entry in self.session_history if entry['blocked'])
        executed_count = total_interactions - blocked_count
        
        duration = datetime.now() - self.session_start
        duration_str = str(duration).split('.')[0]  # Remove microseconds
        
        summary = f"Session Summary:\n"
        summary += f"  Start Time: {self.session_start.strftime('%Y-%m-%d %H:%M:%S')}\n"
        summary += f"  Duration: {duration_str}\n"
        summary += f"  Total Interactions: {total_interactions}\n"
        summary += f"  Commands Executed: {executed_count}\n"
        summary += f"  Commands Blocked: {blocked_count}\n"
        
        if self.log_to_file:
            summary += f"  Log File: {self.log_filename}\n"
        
        return summary
    
    def close_session(self):
        """Close the session and write final summary to log file."""
        if self.log_to_file:
            self._write_to_file("\n" + "=" * 80 + "\n")
            self._write_to_file(self.get_session_summary())
            self._write_to_file("\n" + "=" * 80 + "\n")
